//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 3 files.
  struct file {
    /// Resource file `art.scnassets`.
    static let artScnassets = Rswift.FileResource(bundle: R.hostingBundle, name: "art", pathExtension: "scnassets")
    /// Resource file `wx.jpg`.
    static let wxJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "wx", pathExtension: "jpg")
    /// Resource file `zfb.jpg`.
    static let zfbJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "zfb", pathExtension: "jpg")
    
    /// `bundle.url(forResource: "art", withExtension: "scnassets")`
    static func artScnassets(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.artScnassets
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "wx", withExtension: "jpg")`
    static func wxJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.wxJpg
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "zfb", withExtension: "jpg")`
    static func zfbJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.zfbJpg
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 11 images.
  struct image {
    /// Image `Slice`.
    static let slice = Rswift.ImageResource(bundle: R.hostingBundle, name: "Slice")
    /// Image `add`.
    static let add = Rswift.ImageResource(bundle: R.hostingBundle, name: "add")
    /// Image `help`.
    static let help = Rswift.ImageResource(bundle: R.hostingBundle, name: "help")
    /// Image `logo`.
    static let logo = Rswift.ImageResource(bundle: R.hostingBundle, name: "logo")
    /// Image `restart`.
    static let restart = Rswift.ImageResource(bundle: R.hostingBundle, name: "restart")
    /// Image `set`.
    static let set = Rswift.ImageResource(bundle: R.hostingBundle, name: "set")
    /// Image `setting`.
    static let setting = Rswift.ImageResource(bundle: R.hostingBundle, name: "setting")
    /// Image `settings`.
    static let settings = Rswift.ImageResource(bundle: R.hostingBundle, name: "settings")
    /// Image `trash`.
    static let trash = Rswift.ImageResource(bundle: R.hostingBundle, name: "trash")
    /// Image `wx.jpg`.
    static let wxJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "wx.jpg")
    /// Image `zfb.jpg`.
    static let zfbJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "zfb.jpg")
    
    /// `UIImage(named: "Slice", bundle: ..., traitCollection: ...)`
    static func slice(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.slice, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "add", bundle: ..., traitCollection: ...)`
    static func add(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.add, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "help", bundle: ..., traitCollection: ...)`
    static func help(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.help, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "logo", bundle: ..., traitCollection: ...)`
    static func logo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.logo, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "restart", bundle: ..., traitCollection: ...)`
    static func restart(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.restart, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "set", bundle: ..., traitCollection: ...)`
    static func set(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.set, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "setting", bundle: ..., traitCollection: ...)`
    static func setting(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.setting, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "settings", bundle: ..., traitCollection: ...)`
    static func settings(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.settings, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "trash", bundle: ..., traitCollection: ...)`
    static func trash(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.trash, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "wx.jpg", bundle: ..., traitCollection: ...)`
    static func wxJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.wxJpg, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "zfb.jpg", bundle: ..., traitCollection: ...)`
    static func zfbJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.zfbJpg, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 3 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `licenseCell`.
    static let licenseCell: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "licenseCell")
    /// Reuse identifier `settingCell`.
    static let settingCell: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "settingCell")
    /// Reuse identifier `supportCell`.
    static let supportCell: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "supportCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 1 localization keys.
    struct localizable {
      /// en translation: MOVE YOUR PHONE LEFT AND RIGHT
      /// 
      /// Locales: en, zh-Hans
      static let mOVE = Rswift.StringResource(key: "MOVE", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans"], comment: nil)
      
      /// en translation: MOVE YOUR PHONE LEFT AND RIGHT
      /// 
      /// Locales: en, zh-Hans
      static func mOVE(_: Void = ()) -> String {
        return NSLocalizedString("MOVE", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.main` struct is generated, and contains static references to 0 localization keys.
    struct main {
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
      try launchScreen.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if UIKit.UIImage(named: "logo") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'logo' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let aboutViewController = StoryboardViewControllerResource<AboutViewController>(identifier: "AboutViewController")
      let bundle = R.hostingBundle
      let donateViewController = StoryboardViewControllerResource<DonateViewController>(identifier: "DonateViewController")
      let guideViewController = StoryboardViewControllerResource<UIKit.UIViewController>(identifier: "GuideViewController")
      let name = "Main"
      let questionViewController = StoryboardViewControllerResource<QuestionViewController>(identifier: "QuestionViewController")
      let supportViewController = StoryboardViewControllerResource<SupportViewController>(identifier: "SupportViewController")
      
      func aboutViewController(_: Void = ()) -> AboutViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: aboutViewController)
      }
      
      func donateViewController(_: Void = ()) -> DonateViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: donateViewController)
      }
      
      func guideViewController(_: Void = ()) -> UIKit.UIViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: guideViewController)
      }
      
      func questionViewController(_: Void = ()) -> QuestionViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: questionViewController)
      }
      
      func supportViewController(_: Void = ()) -> SupportViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: supportViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "restart") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'restart' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "trash") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'trash' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "zfb.jpg") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'zfb.jpg' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "add") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'add' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "set") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'set' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "settings") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'settings' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "wx.jpg") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'wx.jpg' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "help") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'help' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "logo") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'logo' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Slice") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Slice' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "setting") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'setting' is used in storyboard 'Main', but couldn't be loaded.") }
        if _R.storyboard.main().donateViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'donateViewController' could not be loaded from storyboard 'Main' as 'DonateViewController'.") }
        if _R.storyboard.main().questionViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'questionViewController' could not be loaded from storyboard 'Main' as 'QuestionViewController'.") }
        if _R.storyboard.main().guideViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'guideViewController' could not be loaded from storyboard 'Main' as 'UIKit.UIViewController'.") }
        if _R.storyboard.main().supportViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'supportViewController' could not be loaded from storyboard 'Main' as 'SupportViewController'.") }
        if _R.storyboard.main().aboutViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'aboutViewController' could not be loaded from storyboard 'Main' as 'AboutViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
